config/routes.rb
Rails.application.routes.draw do
  get 'classroom' => "classroom#index", as: :classroom
  get 'classroom/mates'

  resources :batches
  resources :class_sections
  resources :departments
  resources :posts
  devise_for :admins
  devise_for :faculties, controllers: {
        sessions: 'faculties/sessions'
      }
  devise_for :students, controllers: {
        sessions: 'students/sessions'
      }

  get "profile/:id" => "home#profile", as: :profile
  post "posts#classroom" => "posts#classroom", as: :classroom_post
  root "home#index"

end

app/models/class_section.rb
class ClassSection < ActiveRecord::Base
  belongs_to :department
  has_many :students


  def full_name
  [name, department.name].join(' - ')
end
end

app/controllers/class_sections_controller.rb
class ClassSectionsController < ApplicationController
  before_action :set_class_section, only: [:show, :edit, :update, :destroy]

  # GET /class_sections
  # GET /class_sections.json
  def index
    @class_sections = ClassSection.all
  end

  # GET /class_sections/1
  # GET /class_sections/1.json
  def show
  end

  # GET /class_sections/new
  def new
    @class_section = ClassSection.new
  end

  # GET /class_sections/1/edit
  def edit
  end

  # POST /class_sections
  # POST /class_sections.json
  def create
    @class_section = ClassSection.new(class_section_params)

    respond_to do |format|
      if @class_section.save
        format.html { redirect_to @class_section, notice: 'Class section was successfully created.' }
        format.json { render :show, status: :created, location: @class_section }
      else
        format.html { render :new }
        format.json { render json: @class_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /class_sections/1
  # PATCH/PUT /class_sections/1.json
  def update
    respond_to do |format|
      if @class_section.update(class_section_params)
        format.html { redirect_to @class_section, notice: 'Class section was successfully updated.' }
        format.json { render :show, status: :ok, location: @class_section }
      else
        format.html { render :edit }
        format.json { render json: @class_section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /class_sections/1
  # DELETE /class_sections/1.json
  def destroy
    @class_section.destroy
    respond_to do |format|
      format.html { redirect_to class_sections_url, notice: 'Class section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_class_section
      @class_section = ClassSection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def class_section_params
      params.require(:class_section).permit(:name)
    end
end

app/helpers/class_sections_helper.rb
module ClassSectionsHelper
end

app/views/class_sections/_form.html.erb
<%= form_for(@class_section) do |f| %>
  <% if @class_section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@class_section.errors.count, "error") %> prohibited this class_section from being saved:</h2>

      <ul>
      <% @class_section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/class_sections/edit.html.erb
<h1>Editing Class Section</h1>

<%= render 'form' %>

<%= link_to 'Show', @class_section %> |
<%= link_to 'Back', class_sections_path %>

app/views/class_sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Class Sections</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @class_sections.each do |class_section| %>
      <tr>
        <td><%= class_section.name %></td>
        <td><%= link_to 'Show', class_section %></td>
        <td><%= link_to 'Edit', edit_class_section_path(class_section) %></td>
        <td><%= link_to 'Destroy', class_section, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Class section', new_class_section_path %>

app/views/class_sections/new.html.erb
<h1>New Class Section</h1>

<%= render 'form' %>

<%= link_to 'Back', class_sections_path %>

app/views/class_sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @class_section.name %>
</p>

<%= link_to 'Edit', edit_class_section_path(@class_section) %> |
<%= link_to 'Back', class_sections_path %>