config/routes.rb
Rails.application.routes.draw do
  get 'classroom' => "classroom#index", as: :classroom
  get 'classroom/mates'

  resources :batches
  resources :class_sections
  resources :departments
  resources :posts
  devise_for :admins
  devise_for :faculties, controllers: {
        sessions: 'faculties/sessions'
      }
  devise_for :students, controllers: {
        sessions: 'students/sessions'
      }

  get "profile/:id" => "home#profile", as: :profile
  post "posts#classroom" => "posts#classroom", as: :classroom_post
  root "home#index"

end

app/views/shared/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">SuperVise</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Classroom" , classroom_path %> </li>
        <li class="dropdown">
                <%if student_signed_in? %>
          <a href="#" class="dropdown-toggle profile-image " data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">

            <%= image_tag(current_student.avatar_url,class: "img-circle", width: 30 , height:30 ) %> <%= current_student.name.blank? ? current_student.email : current_student.name  %>  <span class="caret"></span></a>
            <% elsif faculty_signed_in? %>

            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">  <%= current_faculty.email %>  <span class="caret"></span></a>

            <% else %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">  Login/Register  <span class="caret"></span></a>

            <% end %>
          <ul class="dropdown-menu">
            <%if student_signed_in? %>
            <li><%= link_to "Edit Profile", edit_student_registration_path %></li>
            <li><%= link_to "Logout", destroy_student_session_path, :method =>"DELETE" %></li>
            <% elsif faculty_signed_in? %>
                <li><%= link_to "Edit Profile", edit_faculty_registration_path %></li>
                <li><%= link_to "Logout", destroy_faculty_session_path, :method =>"DELETE" %></li>
            <% else %>
            <li><%= link_to "Student Login", new_student_session_path %></li>
            <li><%= link_to "Staff Login", new_faculty_session_path %></li>

            <% end %>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>