config/routes.rb
Rails.application.routes.draw do
  get 'classroom' => "classroom#index", as: :classroom
  get 'classroom/mates'

  resources :batches
  resources :class_sections
  resources :departments
  resources :posts
  devise_for :admins
  devise_for :faculties, controllers: {
        sessions: 'faculties/sessions'
      }
  devise_for :students, controllers: {
        sessions: 'students/sessions'
      }

  get "profile/:id" => "home#profile", as: :profile
  post "posts#classroom" => "posts#classroom", as: :classroom_post
  root "home#index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :student
  mount_uploader :attachment, AvatarUploader

  auto_html_for :message do
    html_escape
    image
    twitter
    google_map
    youtube(:width => 400, :height => 250, :autoplay => false)
    link :target => "_blank", :rel => "nofollow"
    simple_format
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: post }
      else
        format.html { render :new }
        format.json { render json: post.errors, status: :unprocessable_entity }
      end
    end
  end

  def classroom
    @post = Post.new(post_params)
    @post.student_id = current_student.id
    @post.department_id = current_student.department_id
    @post.batch_id = current_student.batch_id
    @post.class_section_id = current_student.class_section_id
    @post.save
    redirect_to :back
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.permit(:message, :faculty_id, :department_id, :year_id, :class_section_id, :attachment)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if classroom %>
<% end %>
<%= form_tag classroom_post_path do %>

  <div class="form-group">
    <%= label_tag :message %><br>
    <%= text_area_tag :message, "",class: "form-control" %>
  </div>

    <div class="form-group">
      <%= label_tag :attachment %><br>
      <%= file_field_tag :attachment,class: "form-control" %>
    </div>
  <div class="form-group">
    <%= submit_tag  "Submit", class: "btn btn-success" %>
  </div>
<% end %>

app/views/posts/_post.html.erb
<% if post.id % 2 == 0 %>
<li>
  <%else %>
  <li class="timeline-inverted">
  <% end %>
         <div class="timeline-badge primary"><a><i class="glyphicon glyphicon-record" rel="tooltip" title="11 hours ago via Twitter" id=""></i></a></div>
         <div class="timeline-panel">
           <div class="timeline-heading">
             <!-- <%= image_tag(post.student.avatar.url, class:"img-responsive") %> -->

           </div>
           <div class="timeline-body">
             <h3><%= post.student.name %></h3>
             <p>
               <%= post.message_html %>
             </p>
           </div>

           <div class="timeline-footer">
               <a><i class="glyphicon glyphicon-thumbs-up"></i></a>
               <% if post.student_id == current_student.id %>
                 <%= link_to post_path(post), method: :delete do %>
                   <i class="glyphicon glyphicon-trash"></i>
                 <% end %>
               <% end %>
               <a class="pull-right"> <%= post.created_at.strftime("%B %d, %Y") %></a>
           </div>
         </div>
       </li>

app/views/posts/classroom.js.erb
alert("successfully Created");

$('.posts-timeline').prepend("<%=j render @post %>");

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', @posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>
      <th>Faculty</th>
      <th>Department</th>
      <th>Year</th>
      <th>Class section</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% posts.each do |post| %>
      <tr>
        <td><%= @post.message %></td>
        <td><%= @post.faculty_id %></td>
        <td><%= @post.department_id %></td>
        <td><%= @post.year_id %></td>
        <td><%= @post.class_section_id %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Message:</strong>
  <%= @post.message %>
</p>

<p>
  <strong>Faculty:</strong>
  <%= @post.faculty_id %>
</p>

<p>
  <strong>Department:</strong>
  <%= @post.department_id %>
</p>

<p>
  <strong>Year:</strong>
  <%= @post.year_id %>
</p>

<p>
  <strong>Class section:</strong>
  <%= @post.class_section_id %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>